/** Mixed JS + TS learning path: alternate fundamentals so learners connect both languages. */
export const mixedSyllabus: Array<{ track: "javascript" | "typescript"; title: string }> = [
  { track: "javascript", title: "JS Tutorial" },
  { track: "typescript", title: "TS Introduction" },
  { track: "javascript", title: "JS Syntax" },
  { track: "typescript", title: "TS Simple Types" },
  { track: "javascript", title: "JS Operators" },
  { track: "typescript", title: "TS Explicit & Inference" },
  { track: "javascript", title: "JS If Conditions" },
  { track: "typescript", title: "TS Special Types" },
  { track: "javascript", title: "JS Loops" },
  { track: "typescript", title: "TS Arrays" },
  { track: "javascript", title: "JS Strings" },
  { track: "typescript", title: "TS Tuples" },
  { track: "javascript", title: "JS Numbers" },
  { track: "typescript", title: "TS Object Types" },
  { track: "javascript", title: "JS Functions" },
  { track: "typescript", title: "TS Functions" },
  { track: "javascript", title: "JS Objects" },
  { track: "typescript", title: "TS Classes" },
  { track: "javascript", title: "JS Scope" },
  { track: "typescript", title: "TS Enums" },
  { track: "javascript", title: "JS Arrays" },
  { track: "typescript", title: "TS Aliases & Interfaces" },
  { track: "javascript", title: "JS Sets" },
  { track: "typescript", title: "TS Union Types" },
  { track: "javascript", title: "JS Maps" },
  { track: "typescript", title: "TS Casting" },
  { track: "javascript", title: "JS Iterations" },
  { track: "typescript", title: "TS Basic Generics" },
  { track: "javascript", title: "JS Math" },
  { track: "typescript", title: "TS Utility Types" },
  { track: "javascript", title: "JS RegExp" },
  { track: "typescript", title: "TS Keyof" },
  { track: "javascript", title: "JS Data Types" },
  { track: "typescript", title: "TS Null" },
  { track: "javascript", title: "JS Errors" },
  { track: "typescript", title: "TS Type Guards" },
  { track: "javascript", title: "JS Debugging" },
  { track: "typescript", title: "TS Conditional Types" },
  { track: "javascript", title: "JS Dates" },
  { track: "typescript", title: "TS Mapped Types" },
  { track: "javascript", title: "JS Temporal" },
  { track: "typescript", title: "TS Type Inference" },
  { track: "javascript", title: "JS Classes" },
  { track: "typescript", title: "TS Literal Types" },
  { track: "javascript", title: "JS Asynchronous" },
  { track: "typescript", title: "TS Async Programming" },
  { track: "javascript", title: "JS Modules" },
  { track: "typescript", title: "TS Modules & Declarations" },
  { track: "javascript", title: "JS Meta & Proxy" },
  { track: "typescript", title: "TS Index Signatures" },
  { track: "javascript", title: "JS Typed Arrays" },
  { track: "typescript", title: "TS Declaration Merging" },
  { track: "javascript", title: "JS HTML DOM" },
  { track: "typescript", title: "TS with React" },
  { track: "javascript", title: "JS HTML Events" },
  { track: "typescript", title: "TS with Node.js" },
  { track: "javascript", title: "JS Web API" },
  { track: "typescript", title: "TS Configuration" },
  { track: "javascript", title: "JS AJAX" },
  { track: "typescript", title: "TS Tooling" },
  { track: "javascript", title: "JS JSON" },
  { track: "typescript", title: "TS 5 Updates" },
  { track: "javascript", title: "JS Advanced" },
  { track: "typescript", title: "TS Advanced Types" },
  { track: "javascript", title: "JS DOM Navigation" },
  { track: "typescript", title: "TS Decorators" },
  { track: "javascript", title: "JS Windows" },
  { track: "typescript", title: "TS in JS Projects" },
  { track: "javascript", title: "JS Projects" },
  { track: "typescript", title: "TS Migration" },
  { track: "javascript", title: "JS Style Guide" },
  { track: "typescript", title: "TS Error Handling" },
  { track: "javascript", title: "JS Examples" },
  { track: "typescript", title: "TS Best Practices" },
  { track: "javascript", title: "JS Reference" },
  { track: "typescript", title: "TS Practice Problems" },
  { track: "typescript", title: "TS Pro: Kickstart Setup" },
  { track: "typescript", title: "TS Pro: Unions and Narrowing" },
  { track: "typescript", title: "TS Pro: Essential Types" },
  { track: "typescript", title: "TS Pro: Generics Deep Dive" },
  { track: "typescript", title: "TS Pro: Configuring TS" },
  { track: "typescript", title: "TS Pro: Designing Types" },
  { track: "typescript", title: "TS Syllabus" },
  { track: "typescript", title: "TS Study Plan" },
  { track: "javascript", title: "JS HTML First" },
  { track: "typescript", title: "TS HOME" },
  { track: "javascript", title: "JS Graphics" },
  { track: "typescript", title: "TS Get Started" },
  { track: "javascript", title: "JS jQuery" },
  { track: "typescript", title: "TS Definitely Typed" },
  { track: "javascript", title: "JS Versions" },
  { track: "typescript", title: "TS Namespaces" },
  { track: "javascript", title: "JS DOM Navigation Advanced" },
  { track: "typescript", title: "TS Certificate Prep" },
  { track: "javascript", title: "JS Performance Patterns" },
  { track: "typescript", title: "TS Editor Workflow" },
  { track: "javascript", title: "JS Security Basics" },
  { track: "typescript", title: "TS Exercises Lab" },
  { track: "javascript", title: "JS Testing Fundamentals" },
  { track: "typescript", title: "TS Quiz Mastery" },
  { track: "javascript", title: "JS Build Tooling Intro" },
  { track: "typescript", title: "TS Type Transformations" },
  { track: "javascript", title: "JS Event Loop Deep Dive" },
  { track: "typescript", title: "TS Branded Types Pattern" },
  { track: "javascript", title: "JS Memory & Closures Pro" },
  { track: "typescript", title: "TS Builder Pattern" },
  { track: "javascript", title: "JS Fetch & REST Clients" },
  { track: "typescript", title: "TS Template Literal Types" },
  { track: "javascript", title: "JS Service Workers Intro" },
  { track: "typescript", title: "TS Satisfies Operator" },
  { track: "javascript", title: "JS Web Components Intro" },
  { track: "typescript", title: "TS Const Type Parameters" },
  { track: "javascript", title: "JS Capstone: Mini App" },
  { track: "typescript", title: "TS Capstone: Typed API Client" },
  { track: "typescript", title: "TS Pro: Type Transformations Workshop" },
  { track: "typescript", title: "TS Pro: Advanced Patterns Workshop" },
  { track: "typescript", title: "TS Pro: React + TS Workshop" },
];
