/**
 * Curriculum aligned with W3Schools JavaScript & TypeScript tutorials.
 * Content is original (not copied); structure mirrors https://www.w3schools.com/js/ and /typescript/
 */

export const w3JavaScriptTopics = [
  "JS Tutorial",
  "JS Syntax",
  "JS Operators",
  "JS If Conditions",
  "JS Loops",
  "JS Strings",
  "JS Numbers",
  "JS Functions",
  "JS Objects",
  "JS Scope",
  "JS Arrays",
  "JS Sets",
  "JS Maps",
  "JS Iterations",
  "JS Math",
  "JS RegExp",
  "JS Data Types",
  "JS Errors",
  "JS Debugging",
  "JS Dates",
  "JS Temporal",
  "JS Classes",
  "JS Asynchronous",
  "JS Modules",
  "JS Meta & Proxy",
  "JS Typed Arrays",
  "JS HTML DOM",
  "JS HTML Events",
  "JS DOM Navigation",
  "JS Windows",
  "JS Web API",
  "JS AJAX",
  "JS JSON",
  "JS Advanced",
  "JS Style Guide",
  "JS Versions",
  "JS HTML First",
  "JS jQuery",
  "JS Graphics",
  "JS Examples",
  "JS Reference",
  "JS Projects",
] as const;

export const w3TypeScriptTopics = [
  "TS Introduction",
  "TS Get Started",
  "TS Simple Types",
  "TS Explicit & Inference",
  "TS Special Types",
  "TS Arrays",
  "TS Tuples",
  "TS Object Types",
  "TS Enums",
  "TS Aliases & Interfaces",
  "TS Union Types",
  "TS Functions",
  "TS Casting",
  "TS Classes",
  "TS Basic Generics",
  "TS Utility Types",
  "TS Keyof",
  "TS Null",
  "TS Definitely Typed",
  "TS Configuration",
  "TS with Node.js",
  "TS with React",
  "TS Tooling",
  "TS Advanced Types",
  "TS Type Guards",
  "TS Conditional Types",
  "TS Mapped Types",
  "TS Type Inference",
  "TS Literal Types",
  "TS Namespaces",
  "TS Index Signatures",
  "TS Declaration Merging",
  "TS Async Programming",
  "TS Decorators",
  "TS in JS Projects",
  "TS Migration",
  "TS Error Handling",
  "TS Best Practices",
  "TS 5 Updates",
  "TS Exercises",
  "TS Quiz",
  "TS Practice Problems",
  "TS Syllabus",
  "TS Study Plan",
] as const;

export const tsProWorkshopTopics = [
  "TS Pro: Setup & Tooling",
  "TS Pro: Essential Types",
  "TS Pro: Unions & Narrowing",
  "TS Pro: Objects & Mutability",
  "TS Pro: Classes",
  "TS Pro: Type Transformations",
  "TS Pro: Generics Deep Dive",
  "TS Pro: Configuring TypeScript",
  "TS Pro: Advanced Patterns",
] as const;

export const w3Syllabus: Array<{ track: "javascript" | "typescript"; title: string }> = [
  ...w3JavaScriptTopics.map((title) => ({ track: "javascript" as const, title })),
  ...w3TypeScriptTopics.map((title) => ({ track: "typescript" as const, title })),
  ...tsProWorkshopTopics.map((title) => ({ track: "typescript" as const, title })),
];
