/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnModuleIdRouteImport } from './routes/learn.$moduleId'
import { Route as ApiSubmitQuizRouteImport } from './routes/api/submit-quiz'
import { Route as ApiSubmitChallengeRouteImport } from './routes/api/submit-challenge'
import { Route as ApiProgressRouteImport } from './routes/api/progress'
import { Route as ApiModulesRouteImport } from './routes/api/modules'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminSyncRouteImport } from './routes/api/admin/sync'
import { Route as ApiAdminProgressRouteImport } from './routes/api/admin/progress'
import { Route as ApiAdminModulesRouteImport } from './routes/api/admin/modules'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnModuleIdRoute = LearnModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => LearnRoute,
} as any)
const ApiSubmitQuizRoute = ApiSubmitQuizRouteImport.update({
  id: '/api/submit-quiz',
  path: '/api/submit-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitChallengeRoute = ApiSubmitChallengeRouteImport.update({
  id: '/api/submit-challenge',
  path: '/api/submit-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressRoute = ApiProgressRouteImport.update({
  id: '/api/progress',
  path: '/api/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModulesRoute = ApiModulesRouteImport.update({
  id: '/api/modules',
  path: '/api/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSyncRoute = ApiAdminSyncRouteImport.update({
  id: '/api/admin/sync',
  path: '/api/admin/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProgressRoute = ApiAdminProgressRouteImport.update({
  id: '/api/admin/progress',
  path: '/api/admin/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminModulesRoute = ApiAdminModulesRouteImport.update({
  id: '/api/admin/modules',
  path: '/api/admin/modules',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/modules': typeof ApiModulesRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/submit-challenge': typeof ApiSubmitChallengeRoute
  '/api/submit-quiz': typeof ApiSubmitQuizRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/learn/': typeof LearnIndexRoute
  '/api/admin/modules': typeof ApiAdminModulesRoute
  '/api/admin/progress': typeof ApiAdminProgressRoute
  '/api/admin/sync': typeof ApiAdminSyncRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/modules': typeof ApiModulesRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/submit-challenge': typeof ApiSubmitChallengeRoute
  '/api/submit-quiz': typeof ApiSubmitQuizRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/learn': typeof LearnIndexRoute
  '/api/admin/modules': typeof ApiAdminModulesRoute
  '/api/admin/progress': typeof ApiAdminProgressRoute
  '/api/admin/sync': typeof ApiAdminSyncRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/modules': typeof ApiModulesRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/submit-challenge': typeof ApiSubmitChallengeRoute
  '/api/submit-quiz': typeof ApiSubmitQuizRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/learn/': typeof LearnIndexRoute
  '/api/admin/modules': typeof ApiAdminModulesRoute
  '/api/admin/progress': typeof ApiAdminProgressRoute
  '/api/admin/sync': typeof ApiAdminSyncRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/learn'
    | '/signin'
    | '/signup'
    | '/api/health'
    | '/api/modules'
    | '/api/progress'
    | '/api/submit-challenge'
    | '/api/submit-quiz'
    | '/learn/$moduleId'
    | '/learn/'
    | '/api/admin/modules'
    | '/api/admin/progress'
    | '/api/admin/sync'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/api/health'
    | '/api/modules'
    | '/api/progress'
    | '/api/submit-challenge'
    | '/api/submit-quiz'
    | '/learn/$moduleId'
    | '/learn'
    | '/api/admin/modules'
    | '/api/admin/progress'
    | '/api/admin/sync'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/learn'
    | '/signin'
    | '/signup'
    | '/api/health'
    | '/api/modules'
    | '/api/progress'
    | '/api/submit-challenge'
    | '/api/submit-quiz'
    | '/learn/$moduleId'
    | '/learn/'
    | '/api/admin/modules'
    | '/api/admin/progress'
    | '/api/admin/sync'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LearnRoute: typeof LearnRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiModulesRoute: typeof ApiModulesRoute
  ApiProgressRoute: typeof ApiProgressRoute
  ApiSubmitChallengeRoute: typeof ApiSubmitChallengeRoute
  ApiSubmitQuizRoute: typeof ApiSubmitQuizRoute
  ApiAdminModulesRoute: typeof ApiAdminModulesRoute
  ApiAdminProgressRoute: typeof ApiAdminProgressRoute
  ApiAdminSyncRoute: typeof ApiAdminSyncRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$moduleId': {
      id: '/learn/$moduleId'
      path: '/$moduleId'
      fullPath: '/learn/$moduleId'
      preLoaderRoute: typeof LearnModuleIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/api/submit-quiz': {
      id: '/api/submit-quiz'
      path: '/api/submit-quiz'
      fullPath: '/api/submit-quiz'
      preLoaderRoute: typeof ApiSubmitQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-challenge': {
      id: '/api/submit-challenge'
      path: '/api/submit-challenge'
      fullPath: '/api/submit-challenge'
      preLoaderRoute: typeof ApiSubmitChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress': {
      id: '/api/progress'
      path: '/api/progress'
      fullPath: '/api/progress'
      preLoaderRoute: typeof ApiProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modules': {
      id: '/api/modules'
      path: '/api/modules'
      fullPath: '/api/modules'
      preLoaderRoute: typeof ApiModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/sync': {
      id: '/api/admin/sync'
      path: '/api/admin/sync'
      fullPath: '/api/admin/sync'
      preLoaderRoute: typeof ApiAdminSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/progress': {
      id: '/api/admin/progress'
      path: '/api/admin/progress'
      fullPath: '/api/admin/progress'
      preLoaderRoute: typeof ApiAdminProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/modules': {
      id: '/api/admin/modules'
      path: '/api/admin/modules'
      fullPath: '/api/admin/modules'
      preLoaderRoute: typeof ApiAdminModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LearnRouteChildren {
  LearnModuleIdRoute: typeof LearnModuleIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnModuleIdRoute: LearnModuleIdRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LearnRoute: LearnRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiModulesRoute: ApiModulesRoute,
  ApiProgressRoute: ApiProgressRoute,
  ApiSubmitChallengeRoute: ApiSubmitChallengeRoute,
  ApiSubmitQuizRoute: ApiSubmitQuizRoute,
  ApiAdminModulesRoute: ApiAdminModulesRoute,
  ApiAdminProgressRoute: ApiAdminProgressRoute,
  ApiAdminSyncRoute: ApiAdminSyncRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
